USE [OLDB89694]
GO
/****** Object:  StoredProcedure [PROYECT].[spDelete]    Script Date: 10/15/2019 22:07:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [PROYECT].[spDelete]
	@ELIMINAR INTEGER,
	@OUTPUT_IS_SUCCESSFUL INT OUTPUT,
	@OUTPUT_IS_STATUS VARCHAR(25) OUTPUT
	AS
BEGIN 
	TRY
		IF (@ELIMINAR=1)
		BEGIN
			DELETE FROM [OLDB89694].[PROYECT].[tblclient] WHERE [tblclient].tblclientmigrate = 1
		END
		ELSE IF (@ELIMINAR=2)
		BEGIN	
			DELETE FROM [OLDB89694].[PROYECT].[tblorder] WHERE [tblorder].tblordermigrate = 1
		END	
		ELSE
		BEGIN
			SET @OUTPUT_IS_STATUS ='Error running'
			SET @OUTPUT_IS_SUCCESSFUL = 0
		END
			
		SET @OUTPUT_IS_STATUS ='Successful running'
		SET @OUTPUT_IS_SUCCESSFUL = 1
	END TRY
	BEGIN CATCH
		SET @OUTPUT_IS_STATUS = @OUTPUT_IS_STATUS +' '+ERROR_MESSAGE()
		SET @OUTPUT_IS_SUCCESSFUL=1
		RAISERROR(@OUTPUT_IS_STATUS,16,1)
	END CATCH 
