CREATE DATABASE [OLDB89694];
USE [OLDB89694];

/*BORRA LOGIN SI EXISTE*/
IF EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'B89694_LOGIN' )
BEGIN
    DROP LOGIN [B89694_LOGIN]; 
END

/*CREA LOGIN SI NO EXISTE*/
IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'B89694_LOGIN' )
BEGIN
    CREATE LOGIN [B89694_LOGIN] WITH PASSWORD = 'A2c3456$#1' MUST_CHANGE, CHECK_EXPIRATION = ON,
	DEFAULT_DATABASE=[OLDB89694], DEFAULT_LANGUAGE=[us_english]; 
END

/*CREA ESQUEMA SI NO EXISTE*/
IF NOT EXISTS (SELECT schema_name 
    FROM information_schema.schemata 
    WHERE schema_name = 'PROYECT' )
BEGIN
    EXEC sp_executesql N'CREATE SCHEMA PROYECT;';
END

/*VERIFICAR SI SE CREÓ EL LOGIN*/
SELECT * FROM sys.sql_logins WHERE name = 'B89694_LOGIN';


/*BORRAR USUARIO*/
/* DROP USER B89694_USER; */

/*CREA ESQUEMA SI NO EXISTE*/
IF USER_ID('B89694_LOGIN') IS NULL
BEGIN
    CREATE USER B89694_USER FOR LOGIN B89694_LOGIN;
END
    
ALTER USER B89694_USER WITH DEFAULT_SCHEMA = [PROYECT];

/*LISTADO DE PERMISOS*/   
/* SELECT * FROM sys.fn_builtin_permissions('SERVER') ORDER BY permission_name; */

/*CREA UN ROL DE USUARIO*/
CREATE ROLE role_B89694 AUTHORIZATION B89694_USER; 

/* ASIGNARLE UN ROL AL LOGIN */
/*sp_dropsrvrolemember  'B89694_LOGIN','bulkadmin';*/
GO
sp_addsrvrolemember 'B89694_LOGIN','sysadmin';
GO

ALTER AUTHORIZATION ON SCHEMA::[PROYECT] TO [B89694_USER]

GO
EXEC sp_addrolemember N'role_B89694', N'B89694_USER'
GO

USE [OLDB89694]
GO
EXEC sp_droprolemember N'db_accessadmin', N'B89694_USER'
GO